services:
  - type: web
    name: kanban-bn
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: sh -c 'if [ -f dist/server.js ]; then node dist/server.js; else node ../dist/server.js; fi'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production